name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

      - run:
          name: Setup dependencies
          command:
            apk add make texlive-xetex ttf-dejavu

      - run:
          name: Build all formats
          command:
            make all

      - run:
          name: Check if epub exists
          command:
            test -s build/epub/book.epub

      - run:
          name: Check if pdf exists
          command:
            test -s build/pdf/book.pdf

